"""Regenerate site/data.js from a real, live run of the secmonitor pipeline.

Run by .github/workflows/weekly-secmonitor-update.yml on a weekly schedule.
Requires two environment variables (set as GitHub Actions secrets in CI,
or exported locally for a manual run):

    SEC_CONTACT_EMAIL       -- any real email; identifies this tool to
                               SEC EDGAR per its fair-access policy.
    ALPHA_VANTAGE_API_KEY   -- optional; adds the real news layer. If unset,
                               the site's news section is simply empty.

Usage:
    SEC_CONTACT_EMAIL=you@example.com python scripts/generate_site_data.py
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from secmonitor.pipeline import MODE_LIVE, run_pipeline  # noqa: E402

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "site" / "data.js"


def build_payload() -> dict:
    contact_email = os.environ.get("SEC_CONTACT_EMAIL")
    if not contact_email:
        raise SystemExit("SEC_CONTACT_EMAIL environment variable is required")
    alpha_vantage_key = os.environ.get("ALPHA_VANTAGE_API_KEY") or None
    print(f"Alpha Vantage key provided: {alpha_vantage_key is not None} "
          f"(length {len(alpha_vantage_key) if alpha_vantage_key else 0})")

    result = run_pipeline(
        mode=MODE_LIVE, contact_email=contact_email, alpha_vantage_key=alpha_vantage_key,
    )

    events = [
        {
            "ticker": e.ticker,
            "company": e.company,
            "category": e.primary_category.label,
            "items": e.items,
            "filed": e.filing_date.isoformat(),
            "materiality": e.materiality,
            "urgency": e.urgency,
            "rationale": e.rationale_joined,
            "accession": e.accession_number,
            "url": e.edgar_url,
        }
        for e in result.events
    ]

    news = [
        {
            "title": n.title,
            "url": n.url,
            "source": n.source,
            "published": n.published.isoformat(),
            "sentiment": n.overall_sentiment_label,
            "tickers": n.tickers,
        }
        for n in result.news
    ]

    return {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "mode": result.mode,
        "coverage_start": result.week_start.isoformat(),
        "coverage_end": result.week_end.isoformat(),
        "universe_size": len(result.sector.tickers),
        "filings_count": len(result.events),
        "companies_with_events": len(result.companies_with_events),
        "silent_count": len(result.sector.tickers) - len(result.companies_with_events),
        "warnings": result.warnings,
        "events": events,
        "news": news,
        "news_warnings": result.news_warnings,
    }


def main() -> None:
    payload = build_payload()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w") as f:
        f.write("// Auto-generated by scripts/generate_site_data.py -- do not edit by hand.\n")
        f.write("window.SECMONITOR_DATA = ")
        json.dump(payload, f, indent=2)
        f.write(";\n")
    print(f"Wrote {OUTPUT_PATH} -- {payload['filings_count']} filings, "
          f"{len(payload['news'])} news items.")


if __name__ == "__main__":
    main()
